export const APPROVED_SOURCES = Object.freeze([
  Object.freeze({
    id: "nasa-earth",
    name: "NASA Earth",
    baseUrl: "https://science.nasa.gov",
    feedUrl: "https://science.nasa.gov/feed/photojournal/latest-content/",
    publisher: "NASA",
    license: { type: "us-federal-public-information", version: null },
    allowedUsage: "facts-and-short-extracts",
    extractScope: "title-summary-link",
    adapter: "rss",
    category: "world",
    topicKind: "evergreen",
  }),
  Object.freeze({
    id: "usgs-publications",
    name: "USGS Publications Warehouse",
    baseUrl: "https://pubs.usgs.gov",
    feedUrl: "https://pubs.usgs.gov/pubs-services/publication/rss/?pub_x_days=60",
    publisher: "U.S. Geological Survey",
    license: { type: "us-federal-public-information", version: null },
    allowedUsage: "facts-and-short-extracts",
    extractScope: "title-summary-link",
    adapter: "rss",
    category: "science",
    topicKind: "evergreen",
  }),
  Object.freeze({
    id: "loc-teachers",
    name: "Teaching with the Library of Congress",
    baseUrl: "https://blogs.loc.gov",
    feedUrl: "https://blogs.loc.gov/teachers/feed/",
    publisher: "Library of Congress",
    license: { type: "facts-only-rights-vary", version: null },
    allowedUsage: "facts-and-short-extracts",
    extractScope: "title-summary-link",
    adapter: "rss",
    category: "humanities",
    topicKind: "evergreen",
  }),
]);
